// Browser metrics are client-originated. Keep detailed numeric pass-through
// fields centralized so local-dev and Worker ingestion expose the same bounded
// measurement surface without accepting arbitrary payload keys.
export const BROWSER_ACTIVITY_NUMERIC_DETAIL_FIELDS = [
  "request_bytes",
  "request_body_bytes",
  "request_known_pages",
  "request_known_page_hash_bytes",
  "request_atom_hashes",
  "request_missing_atoms",
  "request_missing_atom_preimages",
  "request_missing_atom_bytes",
  "request_missing_read_verbs",
  "request_missing_read_props",
  "request_missing_read_contents",
  "request_missing_lifecycle",
  "request_missing_writes",
  "request_missing_other",
  "request_key_atoms",
  "request_key_preimages",
  "request_key_read_verbs",
  "request_key_read_props",
  "request_key_read_contents",
  "request_key_lifecycle",
  "request_key_writes",
  "request_key_other",
  "reply_bytes",
  "reply_metadata_bytes",
  "reply_page_ref_bytes",
  "reply_inline_bytes",
  "reply_preimage_bytes",
  "reply_atom_hash_bytes",
  "reply_page_refs",
  "reply_inline_pages",
  "reply_omitted_pages",
  "reply_preimages",
  "reply_atom_hashes",
  "reply_sessions",
  "reply_logs",
  "reply_snapshots",
  "reply_parked_tasks",
  "reply_tombstones",
  "reply_source_pages",
  "reply_source_objects"
] as const;

